### ISSUE TITLE
Cocoapods version of AssetImportKit: Xcode 10 - linker error: ld: symbol(s) not found for architecture armv7 arm64

### ISSUE THREAD

**Issue by smuravev** [eugenebokhan/AssetImportKit#7]
Hi Eugene,

First thank you very much for awesome framework.
Last days I reconfigured my project to use AssetImportKit framework from Cocoapods. My project is IOS application (Xcode 10 based).
The latest version of AssetImportKit in Cocoapods is v1.0.3.

After I updated from v1.0.1 to v1.0.3 My Xcode always throws linker error. Below you can see the details:

ARMV7 linker issue:
```
ld: warning: ignoring file /Users/sergeymuravev/workspace/prj/vipahelda/configwise/bto-rb-ipd-ios/Pods/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libassimp-iOS.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (armv7): /Users/sergeymuravev/workspace/prj/vipahelda/configwise/bto-rb-ipd-ios/Pods/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libassimp-iOS.a

ld: warning: ignoring file /Users/sergeymuravev/workspace/prj/vipahelda/configwise/bto-rb-ipd-ios/Pods/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libIrrXML-iOS.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (armv7): /Users/sergeymuravev/workspace/prj/vipahelda/configwise/bto-rb-ipd-ios/Pods/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libIrrXML-iOS.a

Undefined symbols for architecture armv7:
  "_aiGetMaterialTexture", referenced from:
      AssetImportKit.TextureInfo.checkTextureType(for: Swift.UnsafeMutablePointer<__C.aiMaterial>, with: __C.aiTextureType, in: __C.aiScene, atPath: __C.NSString, imageCache: AssetImportKit.AssimpImageCache) -> () in TextureInfo.o
  "_aiGetMaterialIntegerArray", referenced from:
      (extension in AssetImportKit):__C.SCNMaterial.loadBlendModeProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + BlendMode.o
      (extension in AssetImportKit):__C.SCNMaterial.loadCullModeProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + CullMode.o
      (extension in AssetImportKit):__C.SCNMaterial.loadLightingModelProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + LightningModel.o
      (extension in AssetImportKit):__C.SCNMaterial.loadShininessProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + Shininess.o
  "_aiImportFile", referenced from:
      function signature specialization <Arg[0] = Exploded> of AssetImportKit.AssetImporter.importScene(filePath: Swift.String, postProcessSteps: AssetImportKit.PostProcessSteps) throws -> AssetImportKit.AssetImporterScene in AssetImporter.o
  "_aiGetMaterialTextureCount", referenced from:
      AssetImportKit.TextureInfo.checkTextureType(for: Swift.UnsafeMutablePointer<__C.aiMaterial>, with: __C.aiTextureType, in: __C.aiScene, atPath: __C.NSString, imageCache: AssetImportKit.AssimpImageCache) -> () in TextureInfo.o
  "_aiReleaseImport", referenced from:
      function signature specialization <Arg[0] = Exploded> of AssetImportKit.AssetImporter.importScene(filePath: Swift.String, postProcessSteps: AssetImportKit.PostProcessSteps) throws -> AssetImportKit.AssetImporterScene in AssetImporter.o
  "_aiGetErrorString", referenced from:
      function signature specialization <Arg[0] = Exploded> of AssetImportKit.AssetImporter.importScene(filePath: Swift.String, postProcessSteps: AssetImportKit.PostProcessSteps) throws -> AssetImportKit.AssetImporterScene in AssetImporter.o
  "_aiGetMaterialString", referenced from:
      function signature specialization <Arg[4] = Dead> of AssetImportKit.AssetImporter.makeMaterials(for: __C.aiNode, in: __C.aiScene, atPath: Swift.String, imageCache: AssetImportKit.AssimpImageCache) -> [__C.SCNMaterial] in AssetImporter.o
      function signature specialization <Arg[5] = Dead> of AssetImportKit.TextureInfo.init(aiMaterial: Swift.UnsafeMutablePointer<__C.aiMaterial>, textureType: __C.aiTextureType, in: __C.aiScene, atPath: __C.NSString, imageCache: AssetImportKit.AssimpImageCache) -> AssetImportKit.TextureInfo in TextureInfo.o
  "_aiGetMaterialColor", referenced from:
      AssetImportKit.AssetImporter.applyMultiplyProperty(for: Swift.UnsafePointer<__C.aiMaterial>, with: __C.SCNMaterial) -> () in AssetImporter.o
      (extension in AssetImportKit):__C.SCNMaterial.loadMultiplyProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + Multiply.o
      AssetImportKit.TextureInfo.extractColor(for: Swift.UnsafeMutablePointer<__C.aiMaterial>, with: __C.aiTextureType) -> () in TextureInfo.o

ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

linker command failed with exit code 1 (use -v to see invocation)
```

ARM64 linker issue:
```
ld: warning: ignoring file /Users/sergeymuravev/workspace/prj/vipahelda/configwise/bto-rb-ipd-ios/Pods/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libassimp-iOS.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/sergeymuravev/workspace/prj/vipahelda/configwise/bto-rb-ipd-ios/Pods/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libassimp-iOS.a

ld: warning: ignoring file /Users/sergeymuravev/workspace/prj/vipahelda/configwise/bto-rb-ipd-ios/Pods/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libIrrXML-iOS.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/sergeymuravev/workspace/prj/vipahelda/configwise/bto-rb-ipd-ios/Pods/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libIrrXML-iOS.a
Undefined symbols for architecture arm64:
  "_aiGetMaterialTexture", referenced from:
      AssetImportKit.TextureInfo.checkTextureType(for: Swift.UnsafeMutablePointer<__C.aiMaterial>, with: __C.aiTextureType, in: __C.aiScene, atPath: __C.NSString, imageCache: AssetImportKit.AssimpImageCache) -> () in TextureInfo.o
  "_aiGetMaterialIntegerArray", referenced from:
      (extension in AssetImportKit):__C.SCNMaterial.loadBlendModeProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + BlendMode.o
      (extension in AssetImportKit):__C.SCNMaterial.loadCullModeProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + CullMode.o
      (extension in AssetImportKit):__C.SCNMaterial.loadLightingModelProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + LightningModel.o
      (extension in AssetImportKit):__C.SCNMaterial.loadShininessProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + Shininess.o
  "_aiImportFile", referenced from:
      function signature specialization <Arg[0] = Exploded> of AssetImportKit.AssetImporter.importScene(filePath: Swift.String, postProcessSteps: AssetImportKit.PostProcessSteps) throws -> AssetImportKit.AssetImporterScene in AssetImporter.o
  "_aiGetMaterialTextureCount", referenced from:
      AssetImportKit.TextureInfo.checkTextureType(for: Swift.UnsafeMutablePointer<__C.aiMaterial>, with: __C.aiTextureType, in: __C.aiScene, atPath: __C.NSString, imageCache: AssetImportKit.AssimpImageCache) -> () in TextureInfo.o
  "_aiReleaseImport", referenced from:
      function signature specialization <Arg[0] = Exploded> of AssetImportKit.AssetImporter.importScene(filePath: Swift.String, postProcessSteps: AssetImportKit.PostProcessSteps) throws -> AssetImportKit.AssetImporterScene in AssetImporter.o
  "_aiGetErrorString", referenced from:
      function signature specialization <Arg[0] = Exploded> of AssetImportKit.AssetImporter.importScene(filePath: Swift.String, postProcessSteps: AssetImportKit.PostProcessSteps) throws -> AssetImportKit.AssetImporterScene in AssetImporter.o
  "_aiGetMaterialString", referenced from:
      function signature specialization <Arg[4] = Dead> of AssetImportKit.AssetImporter.makeMaterials(for: __C.aiNode, in: __C.aiScene, atPath: Swift.String, imageCache: AssetImportKit.AssimpImageCache) -> [__C.SCNMaterial] in AssetImporter.o
      function signature specialization <Arg[5] = Dead> of AssetImportKit.TextureInfo.init(aiMaterial: Swift.UnsafeMutablePointer<__C.aiMaterial>, textureType: __C.aiTextureType, in: __C.aiScene, atPath: __C.NSString, imageCache: AssetImportKit.AssimpImageCache) -> AssetImportKit.TextureInfo in TextureInfo.o
  "_aiGetMaterialColor", referenced from:
      AssetImportKit.AssetImporter.applyMultiplyProperty(for: Swift.UnsafePointer<__C.aiMaterial>, with: __C.SCNMaterial) -> () in AssetImporter.o
      (extension in AssetImportKit):__C.SCNMaterial.loadMultiplyProperty(from: Swift.UnsafePointer<__C.aiMaterial>) -> () in SCNMaterial + Multiply.o
      AssetImportKit.TextureInfo.extractColor(for: Swift.UnsafeMutablePointer<__C.aiMaterial>, with: __C.aiTextureType) -> () in TextureInfo.o

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


linker command failed with exit code 1 (use -v to see invocation)
```

Before, I was using v1.0.1 of your framework (from Cocoapods also) - so, there were NO such linker issues.

Can you please check thi out - maybe any advices from you ?

**Comment by eugenebokhan** [comment]
Thank you for noticing the problem, I'll check that out

**Comment by eugenebokhan** [comment]
Unfortunately I cannot reproduce this issue. Please, try to 

- clean  derrived data

- `pod deintegrate`

- `pod cache clean --all`

- `pod  install`

**Comment by eugenebokhan** [comment]
Unfortunately I still cannot reproduce this issue. Here's the proof:
![v1 0 3](https://user-images.githubusercontent.com/8983647/49683526-a51f3a80-fad7-11e8-8c28-d8e4ee6608e0.gif)
And [here's](https://drive.google.com/file/d/1giOsi2IxOZDhWXMC30npl16L_AUj60aO/view?usp=sharing) the v1.0.3 project with installed pods.

**Comment by eugenebokhan** [comment]
I also tried to install AssetImport on other machines, everything seems to be ok.

**Comment by smuravev** [comment]
Hi Eugene,

Can you please share your Xcode version, Xcode command line tool version and pod tool version (what you use in your environment) ?

**Comment by eugenebokhan** [comment]
Hi, here's what I've got
![screenshot 2018-12-10 at 12 12 25](https://user-images.githubusercontent.com/8983647/49722227-4b547700-fc75-11e8-942e-0285d751c942.png)

**Comment by smuravev** [comment]
Hi Eugene,

Thank you very much for this info - if possible, let's keep this issue open in your tracker - perhaps I know the reason - I have to make couple of experiments to make sure I'm on right way - then I will share results and recommendations what might be fixed in project configurations to avoid issues what I got in my Xcode - maybe this info will be useful for other guys who get the similar issues in their development environments.

Once again - thank you very much for your assistance.

Regards, 
Sergey

**Comment by FreakTheMighty** [comment]
@smuravev did you ever figure this out, I get similar linker errors?

**Comment by eugenebokhan** [comment]
Hi @smuravev!

Here's the info you wanted:
<img width="991" alt="screenshot 2018-12-11 at 08 21 58" src="https://user-images.githubusercontent.com/8983647/49784241-a5187800-fd2d-11e8-9dc2-ac81c40f2cd7.png">

Also there's one thought that came to my mind not long time ago. What if you don't have [`Git LFS`](https://git-lfs.github.com) on your machine? Please check the size of the static libraries that come with the pods, it has to be more than 100 mb for iOS and for macOS targets as well. The assimp static libraries were uploaded with the help of git-lfs, so if you don't have it installed you won't be able to download the full binaries of the libraries. 
You can install git-lfs with the following command:
```ruby
brew install git-lfs
```

Thank you for your help!

**Comment by FreakTheMighty** [comment]
@eugenebokhan your suspicion seems to be partly right. I did not have git lfs to begin with (new computer), but after installing, deleting the Pod cache and Pods folder, the static libraries still do not appear to download. 

The Pods directory contains:

```
./AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/macOS/libassimp-macOS.a
./AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libassimp-iOS.a
```
Where the static files are the git lfs references:
```
version https://git-lfs.github.com/spec/v1
oid sha256:80d08cfdbe300173ca6b084a331cfe117af5ba662cac150b1d109f2e581c449f
size 165413080
```

**Comment by Kelmatou** [comment]
I encountered the same issue, so I used version 1.0.1 (works great thx 👍 ) which is the last version that compiles without errors (I have git-lfs and updated it just to be sure).
Maybe you have something else on your computer that makes your version compile. My step to reproduce is very simple: I downloaded master, opened .xcworkspace, selected scheme AssetImportKit-iOS and cmd+B

**Comment by eugenebokhan** [comment]
@Kelmatou as I understood you are Not able to build the framework from master?

**Comment by Kelmatou** [comment]
Yes that’s it but I didn’t have time to investigate further on what is causing the problem.

**Comment by eugenebokhan** [comment]
@Kelmatou Please tell me the size of assimp static libs in your downloaded directory.

**Comment by eugenebokhan** [comment]
@smuravev @FreakTheMighty @Kelmatou Please check the latest version (1.0.6). I've reduced the size of the static lib and it was uploaded without usage of git-lfs.

**Comment by Kelmatou** [comment]
Ok so, I've clone master, run cmd+B on scheme AssetImportKit-iOS and still the error
```
ld warning: ignoring file  
/Users/antoineclop/Downloads/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libIrrXML-iOS.a,   
file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )   
which is not the architecture being linked (armv7):   
/Users/antoineclop/Downloads/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libIrrXML-iOS.a  
  
ld warning: ignoring file   
/Users/antoineclop/Downloads/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libassimp-iOS.a,   
file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )   
which is not the architecture being linked (armv7):   
/Users/antoineclop/Downloads/AssetImportKit/AssetImportKit/AssetImportKit/Dependencies/Assimp/lib/iOS/libassimp-iOS.a
```
I don't think this is related to git-lfs since static lib is present, but it does not contain symbols for targeted architecture (I've tried with generic iOS device and simulator)
By the way the size of libassimp-iOS.a is 65.1 MB and libIrrXML-iOS.a is 288 KB

**Comment by byzyn4ik** [comment]
@eugenebokhan maybe use prebuild script on pod (s.prepare_command) , which will compile assimp? For iOS 11 and 12 , we need fat binary for 3 archs: (arm64, arm64e, x86_64). I have built fbx-only assimp , and fat binary is 150 mb. 

Also if you don't won't to compile assimp on pod install , we can use lipo on s.prepare_command , it works so fast , this will help us to have up to 100 mb for each platform

**Comment by smuravev** [comment]
Hi @eugenebokhan ,

First, my apologises that no reply from me long time.
Good news - the reason of `linker error: ld: symbol(s) not found for architecture armv7 arm64` was because `git-lfs` extension has not been installed in my environment. Thnx a lot for your recommendations / assistance.

Today, I updated my project to use latest published version of your library `v1.0.8` - it works awesome. Another, benefit of updated library, it's correct rendering (of converted fbx dae files) under IOS 12. It was rendering defect under IOS 12 in case if we convert original fbx, dae files through AssetImportKitLibrary. With `v1.0.8` everything works great. Thnx !
